name: Saber CI
on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"
      - "vcpkg.json"
      - "vcpkg-configuration.json"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"
      - "vcpkg.json"
      - "vcpkg-configuration.json"

env:
  BRANCH_NAME: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'main' }}
  PRERELEASE: ${{ github.ref == 'refs/heads/dev' && 'true' || 'false' }}
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

permissions:
  contents: write
  actions: read

jobs:
  linux:
    name: linux-${{ matrix.arch }}-${{ matrix.config }}-${{ matrix.compiler }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        config: [Release]
        compiler: ["g++-12"]

    env:
      OUTPUT_NAME: saber-linux-${{ matrix.arch }}-${{ matrix.config }}

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: recursive

      - name: Export GitHub Actions cache variables
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build rpm \
            libssl-dev zlib1g-dev linux-libc-dev \
            libtool autoconf pkg-config nasm \
            ${{ matrix.compiler }}

      - name: Install dependencies (vcpkg)
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: x64-linux
          cache-key: linux-${{ matrix.arch }}-${{ matrix.config }}-vcpkg
          token: ${{ github.token }}

      - name: Configure CMake
        run: |
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} \
            -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        env:
          CXX: ${{ matrix.compiler }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }} -j $(nproc)

      - name: Rename binary
        run: mv build/bin/saber build/bin/${{ env.OUTPUT_NAME }}

      - name: Upload Binary
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: build/bin/${{ env.OUTPUT_NAME }}
          if-no-files-found: error

  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        config: [Release]
        vs:
          - { name: 2022, version: 17, os: windows-2022 }

    name: windows-${{ matrix.arch }}-${{ matrix.config }}-vs${{ matrix.vs.name }}
    runs-on: ${{ matrix.vs.os }}

    env:
      OUTPUT_NAME: saber-windows-${{ matrix.arch }}-${{ matrix.config }}.exe

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: recursive

      - name: Export GitHub Actions cache variables
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Install dependencies (vcpkg)
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: ${{ matrix.arch }}-windows-release
          cache-key: windows-${{ matrix.arch }}-${{ matrix.config }}-vcpkg
          token: ${{ github.token }}

      - name: Configure CMake
        run: |
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} `
            -S . -B build `
            -G "Visual Studio ${{ matrix.vs.version }} ${{ matrix.vs.name }}" `
            -A ${{ matrix.arch }} `
            -T host=${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config ${{ matrix.config }} -j $env:NUMBER_OF_PROCESSORS

      - name: Rename binary
        run: Move-Item build/bin/${{ matrix.config }}/saber.exe build/bin/${{ env.OUTPUT_NAME }}

      - name: Upload Binary
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: build/bin/${{ env.OUTPUT_NAME }}
          if-no-files-found: error

  release:
    needs: [linux, windows]
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: recursive

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@778f636ab4ed6f694fb5e2ef1942ea2ae557abf8 # v1.8.0
        with:
          token: ${{ github.token }}
          branch: ${{ env.BRANCH_NAME }}

      - name: Create Draft Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          prerelease: true
          draft: false
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: "*pending*"
          token: ${{ github.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@012e5ba8f4e936cdb2f3b6cd2f81a82cd57a7bf3 # v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          prerelease: ${{ env.PRERELEASE }}
          allowUpdates: true
          draft: false
          makeLatest: true
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

    outputs:
      next: ${{ steps.semver.outputs.next }}

  upload:
    needs: release
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: artifacts

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          repo_token: ${{ github.token }}
          file_glob: true
          file: "artifacts/**/*"
          tag: ${{ needs.release.outputs.next }}
